name: Build Waterfall
on:
  push:
    branches:
      - master
      - actions #temp
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: namespace-profile-linux-default
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v9
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
          cache: "" # namespace handles this
      - name: Set up maven cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: maven
      - name: patch
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./waterfall p
      - name: build
        run: mvn clean install javadoc:javadoc -B
